### ISSUE TITLE
Reuse the clones 

### ISSUE THREAD

**Issue by cattyhouse** [Pavo-IM/opencore_build#1]
Hi Pavo, great script! Would you consider reusing all the clones? Git pull would keep track of latest commits to avoid cloning again for next build.

**Comment by Pavo-IM** [comment]
Not sure I understand what you mean, can you explain?

**Comment by Pavo-IM** [comment]
Do you mean add all of Acidanthera's repos too the script for cloning?

**Comment by cattyhouse** [comment]
This issue was 19days ago, at that time the script deletes dir where clones were in, latest script does not have this issue. Thanks.
